#!/usr/bin/env python3
"""
aggregate.py
============
Collect the per-dataset, per-seed CSVs each runner wrote and emit the
paper-ready artifacts:

  results/<METHOD>_perseed.csv       concatenated (dataset, seed) rows
  results/<METHOD>_multiseed.csv     one row/dataset of 'mean (std)' cells
                                     (METHOD in TEASER, NONMYOPIC, EDEN)
  results/TRUNCATION_perseed.csv     concatenated (dataset, seed, pct) rows
  results/TRUNCATION_multiseed.csv   one row/(dataset, pct) of 'mean (std)' cells
  results/BASELINES_multiseed.csv    long format across the 3 single-cell methods
  results/BASELINES_multiseed.tex    LaTeX snippet (TEASER / NonMyopic / Adaptive RF
                                     rows x 6 dataset cols per metric) + truncation sweep

Run after the SLURM jobs finish:  python aggregate.py
"""
import csv
import mseed_common as mc

METHODS = ["TEASER", "NONMYOPIC", "EDEN"]          # single-cell table row order
METRICS = [("accuracy", "Accuracy (%)"),
           ("precision_weighted", "Precision (weighted)"),
           ("recall_weighted", "Recall (weighted)"),
           ("f1_weighted", "F1 (weighted)"),
           ("savings", "Sensing/Energy Savings (%)")]


def _safe(s):
    return str(s).replace("_", r"\_").replace("%", r"\%")


def main():
    # 1) the three single-cell methods -> combined perseed + multiseed CSVs
    tables = {}
    for m in METHODS:
        mc.combine_perseed(m)
        out, table = mc.write_multiseed_csv(m)
        tables[m] = {t["dataset"]: t for t in table}
        print(f"[{m}] wrote {out.name}  ({len(table)} datasets)")
        for t in table:
            if t["_recall_acc_gap"] > 0.05:
                print(f"  WARN {m}/{t['dataset']}: recall_weighted != accuracy "
                      f"(gap={t['_recall_acc_gap']:.3f})")

    # 2) long-format combined CSV (3 single-cell methods)
    long_path = mc.results_dir() / "BASELINES_multiseed.csv"
    with open(long_path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["method", "method_label", "dataset", "n_seeds",
                    "accuracy", "precision_weighted", "recall_weighted",
                    "f1_weighted", "savings"])
        for m in METHODS:
            for ds in mc.DATASET_ORDER:
                t = tables[m].get(ds)
                if not t:
                    continue
                w.writerow([m, mc.METHOD_LABEL[m], t["display"], t["n_seeds"],
                            t["accuracy"], t["precision_weighted"],
                            t["recall_weighted"], t["f1_weighted"], t["savings"]])
    print(f"[all] wrote {long_path.name}")

    # 3) static-truncation sweep -> combined perseed + per-(dataset,pct) multiseed
    trunc = mc.trunc_multiseed_table()
    if trunc:
        # combined perseed
        by = mc.load_trunc_perseed()
        with open(mc.trunc_perseed_path(), "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=mc.TRUNC_FIELDS)
            w.writeheader()
            for ds in mc.DATASET_ORDER:
                for pct in mc.TRUNC_PERCENTAGES:
                    for r in sorted(by.get((ds, pct), []), key=lambda x: int(x["seed"])):
                        w.writerow({k: r[k] for k in mc.TRUNC_FIELDS})
        # multiseed sweep
        tpath = mc.results_dir() / "TRUNCATION_multiseed.csv"
        with open(tpath, "w", newline="") as fh:
            w = csv.writer(fh)
            w.writerow(["dataset", "pct", "n_seeds", "accuracy", "precision_weighted",
                        "recall_weighted", "f1_weighted", "savings"])
            for t in trunc:
                w.writerow([t["display"], t["pct"], t["n_seeds"], t["accuracy"],
                            t["precision_weighted"], t["recall_weighted"],
                            t["f1_weighted"], t["savings"]])
        print(f"[TRUNCATION] wrote {tpath.name}  ({len(trunc)} dataset x pct rows)")

    # 4) LaTeX snippet: one tabular per metric (methods x datasets) + truncation sweep
    cols = [mc.DISPLAY[d] for d in mc.DATASET_ORDER]
    lines = [
        "% BASELINES_multiseed.tex -- auto-generated by aggregate.py",
        "% mean (std) over seeds 42-46; std = sample std (ddof=1).",
        "% Accuracy & Savings: percent, 1 decimal.  P/R/F1: weighted, 3 decimals.",
        "% recall_weighted == accuracy by construction.",
        "% Single-cell methods fill the TEASER / NonMyopic / Adaptive RF rows.",
        "",
    ]
    for key, label in METRICS:
        lines.append(f"% ---- {label} ----")
        lines.append(r"\begin{tabular}{l" + "c" * len(cols) + "}")
        lines.append(r"\toprule")
        lines.append("Method & " + " & ".join(_safe(c) for c in cols) + r" \\")
        lines.append(r"\midrule")
        for m in METHODS:
            cells = [(_safe(tables[m][ds][key]) if tables[m].get(ds) else "--")
                     for ds in mc.DATASET_ORDER]
            lines.append(f"{_safe(mc.METHOD_LABEL[m])} & " + " & ".join(cells) + r" \\")
        lines.append(r"\bottomrule")
        lines.append(r"\end{tabular}")
        lines.append("")
    if trunc:
        lines.append("% ==== Static Truncation (RF) sweep -- Accuracy (%) mean (std) ====")
        lines.append(r"\begin{tabular}{l" + "c" * len(mc.TRUNC_PERCENTAGES) + "}")
        lines.append(r"\toprule")
        lines.append("Dataset & " + " & ".join(f"{p}\\%" for p in mc.TRUNC_PERCENTAGES) + r" \\")
        lines.append(r"\midrule")
        by_disp = {}
        for t in trunc:
            by_disp.setdefault(t["display"], {})[t["pct"]] = t["accuracy"]
        for ds in mc.DATASET_ORDER:
            disp = mc.DISPLAY[ds]
            if disp not in by_disp:
                continue
            cells = [_safe(by_disp[disp].get(p, "--")) for p in mc.TRUNC_PERCENTAGES]
            lines.append(f"{_safe(disp)} & " + " & ".join(cells) + r" \\")
        lines.append(r"\bottomrule")
        lines.append(r"\end{tabular}")
        lines.append("")
    tex_path = mc.results_dir() / "BASELINES_multiseed.tex"
    tex_path.write_text("\n".join(lines))
    print(f"[all] wrote {tex_path.name}")

    # 5) console preview
    print("\n=== multi-seed summary (mean (std)) ===")
    print(f"{'method':<22}{'dataset':<10}{'acc%':>14}{'P_w':>16}{'F1_w':>16}{'sav%':>14}")
    for m in METHODS:
        for ds in mc.DATASET_ORDER:
            t = tables[m].get(ds)
            if not t:
                continue
            print(f"{mc.METHOD_LABEL[m]:<22}{t['display']:<10}{t['accuracy']:>14}"
                  f"{t['precision_weighted']:>16}{t['f1_weighted']:>16}{t['savings']:>14}")
    if trunc:
        print("\n=== static truncation sweep (acc% mean (std)) ===")
        for t in trunc:
            print(f"{'StaticTrunc':<22}{t['display']:<7}{t['pct']:>3}%{t['accuracy']:>16}"
                  f"{t['f1_weighted']:>16}{t['savings']:>14}")


if __name__ == "__main__":
    main()
